server:
    port: 8081
spring:
    application:
        name: =CUSTOMER-WS
    datasource:
        password: root
        url: jdbc:h2:mem:testdb
        username: root
    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
